package View;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.border.Border;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

import Controller.AddQuestionController;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

public class AddQuestionView extends javax.swing.JFrame {
	

	private static final long serialVersionUID = 1L;
	private JPanel contentPane;
	private JTextField obtion1TeksField;
	private String k;
	private JTextField questionTextField;
	private JTextField obtion3textField;
	private JTextField obtion2TextField;
	private JTextField obtion4textField;
	private JButton save;
	@SuppressWarnings("rawtypes")
	private JComboBox<Comparable> comboBox;
	private JRadioButton easy;
	private JRadioButton medium;
	private JRadioButton hard;
	private JButton backButton;
	private AddQuestionController controller = AddQuestionController.getInstance();



    /**
     * Creates new form Login
     */
    public AddQuestionView() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }
    
    public ImageIcon resized(Image image, int weight, int height) {
		 Image backImage = image;
	        Image resized = backImage.getScaledInstance(weight, height, Image.SCALE_SMOOTH);
	        ImageIcon resizeds = new ImageIcon(resized);
		
		return resizeds;
		
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new Background();
        
        /***************Question Panel******************/

        JPanel questionPanel = new JPanel();
        questionPanel.setBounds(192, 124, 630, 51);
        questionPanel.setLayout(null);
        questionPanel.setBackground(new Color(139, 69, 19, 140));
        Border border1 = BorderFactory.createLineBorder(Color.white, 1);
        questionPanel.setBorder(border1);
        background.add(questionPanel);

        JLabel questionLabel = new JLabel("Question:");
        questionLabel.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/questionIcon1.png")));
        questionLabel.setForeground(Color.WHITE);
        questionLabel.setBounds(10, 15, 162, 25);
        questionPanel.add(questionLabel);
        questionLabel.setFont(new Font("Kristen ITC", Font.PLAIN, 14));

       // questionTextField = new JTextField();
        questionTextField = new JTextField() {
            @Override
            protected Document createDefaultModel() {
                return new PlainDocument() {
                    @Override
                    public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                        if (str == null) {
                            return;
                        }
                        String currentText = getText(0, getLength());
                        String newText = currentText.substring(0, offs) + str + currentText.substring(offs);
                        if (newText.matches("(?!\\s+$)[a-zA-Z0-9\\s]+")) {
                            super.insertString(offs, str, a);
                        }
                    }
                };
            }
        };

        questionTextField.setText((String) null);
        
        questionTextField.setColumns(10);
        questionTextField.setBounds(126, 14, 494, 28);
        questionPanel.add(questionTextField);
        
        /********************Choices Panel*************************/
		JPanel choicesPanel = new JPanel();
		choicesPanel.setBounds(192, 183, 630, 150);
		choicesPanel.setLayout(null);
		choicesPanel.setBackground(new Color(139, 69, 19, 140));
		Border border = BorderFactory.createLineBorder(Color.white, 1);
		choicesPanel.setBorder(border);		
		background.add(choicesPanel);
		
		 JLabel choices = new JLabel("Choices:");
	     choices.setForeground(Color.WHITE);
	     choices.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/choices.png")));
	     choices.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
	     choices.setBounds(10, 16, 162, 25);
	     choicesPanel.add(choices);
		
		JLabel obtion1 = new JLabel("Obtion 1");
	    obtion1.setForeground(Color.WHITE);
	    obtion1.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans1.png")));
	    obtion1.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
	    obtion1.setBounds(10, 53, 103, 25);
	    choicesPanel.add(obtion1);
	     
	    obtion1TeksField = new JTextField(){
            @Override
            protected Document createDefaultModel() {
                return new PlainDocument() {
                    @Override
                    public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                        if (str == null) {
                            return;
                        }
                        String currentText = getText(0, getLength());
                        String newText = currentText.substring(0, offs) + str + currentText.substring(offs);
                        if (newText.matches("(?!\\s+$)[a-zA-Z0-9\\s]+")) {
                            super.insertString(offs, str, a);
                        }
                    }
                };
            }
        };

	    obtion1TeksField.setColumns(10);
	    obtion1TeksField.setText(k);
	    obtion1TeksField.setBounds(106, 52, 197, 28);
	    choicesPanel.add(obtion1TeksField);
		
		JLabel obtion2 = new JLabel("Obtion 2");
		obtion2.setForeground(Color.WHITE);
	    obtion2.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans2.png")));
		obtion2.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		obtion2.setBounds(10, 102, 94, 25);
		choicesPanel.add(obtion2);
		
		obtion2TextField = new JTextField(){
            @Override
            protected Document createDefaultModel() {
                return new PlainDocument() {
                    @Override
                    public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                        if (str == null) {
                            return;
                        }
                        String currentText = getText(0, getLength());
                        String newText = currentText.substring(0, offs) + str + currentText.substring(offs);
                        if (newText.matches("(?!\\s+$)[a-zA-Z0-9\\s]+")) {
                            super.insertString(offs, str, a);
                        }
                    }
                };
            }
        };

	    obtion2TextField.setText((String) null);
	    obtion2TextField.setColumns(10);
	    obtion2TextField.setBounds(106, 101, 197, 28);
	    choicesPanel.add(obtion2TextField);
		
		JLabel obtion3 = new JLabel("Obtion 3");
		obtion3.setForeground(Color.WHITE);
	    obtion3.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans3.png")));
		obtion3.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		obtion3.setBounds(314, 53, 118, 25);
		choicesPanel.add(obtion3);
		
		obtion3textField = new JTextField(){
            @Override
            protected Document createDefaultModel() {
                return new PlainDocument() {
                    @Override
                    public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                        if (str == null) {
                            return;
                        }
                        String currentText = getText(0, getLength());
                        String newText = currentText.substring(0, offs) + str + currentText.substring(offs);
                        if (newText.matches("(?!\\s+$)[a-zA-Z0-9\\s]+")) {
                            super.insertString(offs, str, a);
                        }
                    }
                };
            }
        };

	    obtion3textField.setText((String) null);
	    obtion3textField.setColumns(10);
	    obtion3textField.setBounds(423, 52, 197, 28);
	    choicesPanel.add(obtion3textField);
		
		JLabel obtion4 = new JLabel("Obtion 4");
		obtion4.setForeground(Color.WHITE);
	    obtion4.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans4.png")));
		obtion4.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		obtion4.setBounds(313, 102, 118, 25);
		choicesPanel.add(obtion4);
		
	    obtion4textField = new JTextField(){
            @Override
            protected Document createDefaultModel() {
                return new PlainDocument() {
                    @Override
                    public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                        if (str == null) {
                            return;
                        }
                        String currentText = getText(0, getLength());
                        String newText = currentText.substring(0, offs) + str + currentText.substring(offs);
                        if (newText.matches("(?!\\s+$)[a-zA-Z0-9\\s]+")) {
                            super.insertString(offs, str, a);
                        }
                    }
                };
            }
        };

	    obtion4textField.setText((String) null);
	    obtion4textField.setColumns(10);
	    obtion4textField.setBounds(423, 101, 197, 28);
	    choicesPanel.add(obtion4textField);
	    
	    /*********************Correct Answer & Difficulty*********************************/
		JPanel correctDiffPanel = new JPanel();
		correctDiffPanel.setLayout(null);
		correctDiffPanel.setBounds(190, 340, 630, 110);
		correctDiffPanel.setBackground(new Color(139, 69, 19, 140));
		Border border2 = BorderFactory.createLineBorder(Color.white, 1);
		correctDiffPanel.setBorder(border2);
		background.add(correctDiffPanel);
			
		JLabel correctAns = new JLabel("Correct Answer:");
		correctAns.setForeground(Color.WHITE);
		correctAns.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/correctAns.png")));
		correctAns.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		correctAns.setBounds(10, 15, 162, 25);
		correctDiffPanel.add(correctAns);
		
		comboBox = new JComboBox<Comparable>();
		comboBox.setBounds(162, 17, 84, 22);
		comboBox.addItem("...");
		comboBox.addItem(1);
		comboBox.addItem(2);
		comboBox.addItem(3);
		comboBox.addItem(4);
		correctDiffPanel.add(comboBox);
			
		JLabel difficulty = new JLabel("Difficulty:");
		difficulty.setForeground(Color.WHITE);
		difficulty.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/difficulty.png")));
		difficulty.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		difficulty.setBounds(286, 15, 122, 25);
		correctDiffPanel.add(difficulty);
		
		ButtonGroup buttonGroup = new ButtonGroup();
			
		easy = new JRadioButton("Easy");
		easy.setForeground(Color.WHITE);
		easy.setBackground(new Color(0, 0, 0, 140));
		easy.setBounds(402, 17, 60, 23);
		correctDiffPanel.add(easy);
			
		medium = new JRadioButton("Medium");
		medium.setBackground(new Color(0, 0, 0, 140));
		medium.setForeground(Color.WHITE);
		medium.setBounds(402, 47, 77, 23);
		correctDiffPanel.add(medium);
			
		hard = new JRadioButton("Hard");
		hard.setBackground(new Color(0, 0, 0, 140));
		hard.setForeground(Color.WHITE);
		hard.setBounds(402, 73, 60, 23);
		correctDiffPanel.add(hard);
		
		buttonGroup.add(easy);
		buttonGroup.add(medium);
		buttonGroup.add(hard);
		
		JLabel easyIcon = new JLabel("");
		easyIcon.setForeground(Color.WHITE);
		easyIcon.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/easy2.png")));

		easyIcon.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		easyIcon.setBounds(462, 15, 36, 25);
		correctDiffPanel.add(easyIcon);
		
		JLabel mediumIcon = new JLabel("");
		mediumIcon.setForeground(Color.WHITE);
		mediumIcon.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/med.png")));

		mediumIcon.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		mediumIcon.setBounds(487, 47, 36, 25);
		correctDiffPanel.add(mediumIcon);
		
		JLabel hardIcon = new JLabel("");
		hardIcon.setForeground(Color.WHITE);
		hardIcon.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/hard1.png")));

		hardIcon.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		hardIcon.setBounds(468, 71, 30, 25);
		correctDiffPanel.add(hardIcon);
		
		questionLabel_1 = new JLabel("NEW QUESTION");
        questionLabel_1.setForeground(Color.WHITE);
        questionLabel_1.setBounds(280, 20, 500, 50);
        questionLabel_1.setFont(new Font("Gill Sans Ultra Bold", Font.BOLD, 45));
        background.add(questionLabel_1);
        
    	JLabel homePage = new JLabel();
    	//	homePage.setIcon(new ImageIcon(ChooseGame1.class.getResource("/img/rectangle.png")));		
    		homePage.setBounds(90, 40, 90, 90);
    		homePage.setLayout(null);
    		
    		ImageIcon ImageIconHome = new ImageIcon(ChooseGame1.class.getResource("/img/backIcon.png"));
    		ImageIcon testHome= resized(ImageIconHome.getImage(), 90, 90);
    		homePage.setIcon(testHome);
    		background.add(homePage);
    		homePage.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    // Open HomeView and close the current view
                	if(!(comboBox.getSelectedItem().equals("..."))||!(questionTextField.getText().isEmpty())|| !(obtion1TeksField.getText().isEmpty())|| !(obtion2TextField.getText().isEmpty()) || !(obtion3textField.getText().isEmpty()) || !(obtion3textField.getText().isEmpty())
        					|| !((!easy.isSelected() && !medium.isSelected() && !hard.isSelected()))) {
        				 int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you don't want to continue?", "Confirmation", JOptionPane.YES_NO_OPTION);
        				 if(confirmation==JOptionPane.YES_OPTION) {
        						QuestionsView QuestionViewPage = new QuestionsView();
        						QuestionViewPage.setVisible(true);
        						dispose();
        				 }
        			}
        			else {
        				QuestionsView QuestionViewPage = new QuestionsView();
        				QuestionViewPage.setVisible(true);
        				dispose();
        			}
                }
            });
		
    		JLabel addQuestion = new JLabel();
        	//	homePage.setIcon(new ImageIcon(ChooseGame1.class.getResource("/img/rectangle.png")));		
    		addQuestion.setBounds(450, 470, 90, 90);
    		addQuestion.setLayout(null);
    		
        		
        		ImageIcon ImageIconQue = new ImageIcon(ChooseGame1.class.getResource("/img/addQ1.png"));
        		ImageIcon testQue= resized(ImageIconQue.getImage(), 90, 90);
        		addQuestion.setIcon(testQue);
        		background.add(addQuestion);
        		addQuestion.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                    	int q=0;
            			try {
            				/*check if the admin full all the text field and if not nullPointerException will throw*/
            				if(comboBox.getSelectedItem().equals("...")|| questionTextField.getText().trim().isEmpty()|| obtion1TeksField.getText().trim().isEmpty() || obtion2TextField.getText().trim().isEmpty() || obtion3textField.getText().trim().isEmpty() || obtion4textField.getText().trim().isEmpty()
            						 ||(!easy.isSelected() && !medium.isSelected() && !hard.isSelected())) {
            					throw new NullPointerException("return value is null");
            				}		
            				} catch( NullPointerException e2) {
            					q=1;
            					JOptionPane.showMessageDialog(null, "full all field!",
            							"warning", JOptionPane.WARNING_MESSAGE);
            				}
            			if(q==0) {
            				List<String> answers = new ArrayList<String>(); //holds the question�s answers.
            				String questionBody;
            				questionBody= (String)questionTextField.getText();
            				
            				Boolean n=controller.isDulicated(questionBody);
            				if (n==true) {
            	                JOptionPane.showMessageDialog(null, "This question is exists.", "Error", JOptionPane.ERROR_MESSAGE);
            	                return;
            				}
            				
            				String answer1 = obtion1TeksField.getText().trim();
            		        String answer2 = obtion2TextField.getText().trim();
            		        String answer3 = obtion3textField.getText().trim();
            		        String answer4 = obtion4textField.getText().trim();
            				 
            		         if (answer1.equals(answer2) || answer1.equals(answer3) || answer1.equals(answer4) ||
            		                    answer2.equals(answer3) || answer2.equals(answer4) || answer3.equals(answer4)) {
            		                JOptionPane.showMessageDialog(null, "All answers should be different.", "Error", JOptionPane.ERROR_MESSAGE);
            		                return;
            		            }
            		         else {
            		        	 answers.add(answer1);
            		        	 answers.add(answer2);
            		        	 answers.add(answer3);
            		        	 answers.add(answer4);
            		         }
            		         
            		         int difficulty = 0;
            		         if (easy.isSelected()) {
            		        	    difficulty = 1;
            		        	} else if (medium.isSelected()) {
            		        	    difficulty = 2;
            		        	} else if (hard.isSelected()) {
            		        	    difficulty = 3;
            		        	}
            		         
            		         int correctAns=(int) comboBox.getSelectedItem();
            		         try {
            			         controller.addQuestion(questionBody, answers, correctAns, difficulty);
            			         // Show a message dialog to inform the user about successful addition
            			         JOptionPane.showMessageDialog(AddQuestionView.this, "Question added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            			         
            			         // Navigate back to the Test page
            			         QuestionsView testPage = new QuestionsView();
            			         testPage.setVisible(true);
            			         dispose(); // Close the current window

            		        	} catch (Exception e2) {
            		        	    // Display a message dialog to inform the user about the error
            		        	    JOptionPane.showMessageDialog(AddQuestionView.this, "Failed to add question: " + e2.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            		        	    e2.printStackTrace(); // Print the stack trace for debugging purposes
            		        	}

            		        	 
            			}
                    }
                });
    		
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        backgroundLayout.setHorizontalGroup(
        	backgroundLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 952, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
        	backgroundLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 618, Short.MAX_VALUE)
        );
        background.setLayout(backgroundLayout);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(238)
        			.addComponent(background, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(68))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(background, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Background background;
    private JLabel questionLabel_1;
}