package View;

import java.awt.Color;
import java.awt.Font;

import javax.swing.GroupLayout.Alignment;
import javax.swing.border.Border;

import Controller.AddQuestionController;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author RAVEN
 */
public class Login extends javax.swing.JFrame {
	

	private static final long serialVersionUID = 1L;
	private JPanel contentPane;
	private JTextField obtion1TeksField;
	private String k;
	private JTextField questionTextField;
	private JTextField obtion3textField;
	private JTextField obtion2TextField;
	private JTextField obtion4textField;
	private JButton save;
	@SuppressWarnings("rawtypes")
	private JComboBox<Comparable> comboBox;
	private JRadioButton easy;
	private JRadioButton medium;
	private JRadioButton hard;
	private JButton backButton;
	private AddQuestionController controller = AddQuestionController.getInstance();



    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new Background();
        
        /***************Question Panel******************/

        JPanel questionPanel = new JPanel();
        questionPanel.setBounds(192, 124, 630, 51);
        questionPanel.setLayout(null);
        questionPanel.setBackground(new Color(139, 69, 19, 140));
        Border border1 = BorderFactory.createLineBorder(Color.white, 1);
        questionPanel.setBorder(border1);
        background.add(questionPanel);

        JLabel questionLabel = new JLabel("Question:");
        questionLabel.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/questionIcon1.png")));
        questionLabel.setForeground(Color.WHITE);
        questionLabel.setBounds(10, 15, 162, 25);
        questionPanel.add(questionLabel);
        questionLabel.setFont(new Font("Kristen ITC", Font.PLAIN, 14));

        questionTextField = new JTextField();
        questionTextField.setText((String) null);
        questionTextField.setColumns(10);
        questionTextField.setBounds(126, 14, 494, 28);
        questionPanel.add(questionTextField);
        
        /********************Choices Panel*************************/
		JPanel choicesPanel = new JPanel();
		choicesPanel.setBounds(192, 183, 630, 150);
		choicesPanel.setLayout(null);
		choicesPanel.setBackground(new Color(139, 69, 19, 140));
		Border border = BorderFactory.createLineBorder(Color.white, 1);
		choicesPanel.setBorder(border);		
		background.add(choicesPanel);
		
		 JLabel choices = new JLabel("Choices:");
	     choices.setForeground(Color.WHITE);
	     choices.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/choices.png")));
	     choices.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
	     choices.setBounds(10, 16, 162, 25);
	     choicesPanel.add(choices);
		
		JLabel obtion1 = new JLabel("Obtion 1");
	    obtion1.setForeground(Color.WHITE);
	    obtion1.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans1.png")));
	    obtion1.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
	    obtion1.setBounds(10, 53, 103, 25);
	    choicesPanel.add(obtion1);
	     
	    obtion1TeksField = new JTextField();
	    obtion1TeksField.setColumns(10);
	    obtion1TeksField.setText(k);
	    obtion1TeksField.setBounds(106, 52, 197, 28);
	    choicesPanel.add(obtion1TeksField);
		
		JLabel obtion2 = new JLabel("Obtion 2");
		obtion2.setForeground(Color.WHITE);
	    obtion2.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans2.png")));
		obtion2.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		obtion2.setBounds(10, 102, 94, 25);
		choicesPanel.add(obtion2);
		
		obtion2TextField = new JTextField();
	    obtion2TextField.setText((String) null);
	    obtion2TextField.setColumns(10);
	    obtion2TextField.setBounds(106, 101, 197, 28);
	    choicesPanel.add(obtion2TextField);
		
		JLabel obtion3 = new JLabel("Obtion 3");
		obtion3.setForeground(Color.WHITE);
	    obtion3.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans3.png")));
		obtion3.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		obtion3.setBounds(314, 53, 118, 25);
		choicesPanel.add(obtion3);
		
		obtion3textField = new JTextField();
	    obtion3textField.setText((String) null);
	    obtion3textField.setColumns(10);
	    obtion3textField.setBounds(423, 52, 197, 28);
	    choicesPanel.add(obtion3textField);
		
		JLabel obtion4 = new JLabel("Obtion 4");
		obtion4.setForeground(Color.WHITE);
	    obtion4.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/ans4.png")));
		obtion4.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		obtion4.setBounds(313, 102, 118, 25);
		choicesPanel.add(obtion4);
		
	    obtion4textField = new JTextField();
	    obtion4textField.setText((String) null);
	    obtion4textField.setColumns(10);
	    obtion4textField.setBounds(423, 101, 197, 28);
	    choicesPanel.add(obtion4textField);
	    
	    /*********************Correct Answer & Difficulty*********************************/
		JPanel correctDiffPanel = new JPanel();
		correctDiffPanel.setLayout(null);
		correctDiffPanel.setBounds(190, 340, 630, 110);
		correctDiffPanel.setBackground(new Color(139, 69, 19, 140));
		Border border2 = BorderFactory.createLineBorder(Color.white, 1);
		correctDiffPanel.setBorder(border2);
		background.add(correctDiffPanel);
			
		JLabel correctAns = new JLabel("Correct Answer:");
		correctAns.setForeground(Color.WHITE);
		correctAns.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/correctAns.png")));
		correctAns.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		correctAns.setBounds(10, 15, 162, 25);
		correctDiffPanel.add(correctAns);
		
		comboBox = new JComboBox<Comparable>();
		comboBox.setBounds(162, 17, 84, 22);
		comboBox.addItem("...");
		comboBox.addItem(1);
		comboBox.addItem(2);
		comboBox.addItem(3);
		comboBox.addItem(4);
		correctDiffPanel.add(comboBox);
			
		JLabel difficulty = new JLabel("Difficulty:");
		difficulty.setForeground(Color.WHITE);
		difficulty.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/difficulty.png")));
		difficulty.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		difficulty.setBounds(286, 15, 122, 25);
		correctDiffPanel.add(difficulty);
		
		ButtonGroup buttonGroup = new ButtonGroup();
			
		easy = new JRadioButton("Easy");
		easy.setForeground(Color.WHITE);
		easy.setBackground(new Color(0, 0, 0, 140));
		easy.setBounds(402, 17, 60, 23);
		correctDiffPanel.add(easy);
			
		medium = new JRadioButton("Medium");
		medium.setBackground(new Color(0, 0, 0, 140));
		medium.setForeground(Color.WHITE);
		medium.setBounds(402, 47, 77, 23);
		correctDiffPanel.add(medium);
			
		hard = new JRadioButton("Hard");
		hard.setBackground(new Color(0, 0, 0, 140));
		hard.setForeground(Color.WHITE);
		hard.setBounds(402, 73, 60, 23);
		correctDiffPanel.add(hard);
		
		buttonGroup.add(easy);
		buttonGroup.add(medium);
		buttonGroup.add(hard);
		
		JLabel easyIcon = new JLabel("");
		easyIcon.setForeground(Color.WHITE);
		easyIcon.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/easy2.png")));

		easyIcon.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		easyIcon.setBounds(462, 15, 36, 25);
		correctDiffPanel.add(easyIcon);
		
		JLabel mediumIcon = new JLabel("");
		mediumIcon.setForeground(Color.WHITE);
		mediumIcon.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/med.png")));

		mediumIcon.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		mediumIcon.setBounds(487, 47, 36, 25);
		correctDiffPanel.add(mediumIcon);
		
		JLabel hardIcon = new JLabel("");
		hardIcon.setForeground(Color.WHITE);
		hardIcon.setIcon(new ImageIcon(AddQuestionView.class.getResource("/img/hard1.png")));

		hardIcon.setFont(new Font("Kristen ITC", Font.PLAIN, 14));
		hardIcon.setBounds(468, 71, 30, 25);
		correctDiffPanel.add(hardIcon);
		
		questionLabel_1 = new JLabel("NEW QUESTION");
        questionLabel_1.setForeground(Color.WHITE);
        questionLabel_1.setBounds(280, 20, 500, 50);
        questionLabel_1.setFont(new Font("Gill Sans Ultra Bold", Font.BOLD, 45));
        background.add(questionLabel_1);
		


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        backgroundLayout.setHorizontalGroup(
        	backgroundLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 952, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
        	backgroundLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 618, Short.MAX_VALUE)
        );
        background.setLayout(backgroundLayout);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(238)
        			.addComponent(background, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(68))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(background, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Background background;
    private JLabel questionLabel_1;
}